flowers_shop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path

from main import views

urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('filials/', views.filials, name='filials'),
    path('products/', views.products, name='products'),
    path('services/', views.services, name='services'),
    path('orders/<int:pk>/', views.orders, name='orders'),
    path('create_supply/<int:pk>/', views.create_supply, name='create_supply'),
    path('supply-list/', views.supply_list, name='supply_list'),
    path('write_offs/<int:pk>/', views.write_offs, name='write_offs'),
    path('sales/<int:pk>/', views.sales, name='sales'),
    path('create_service_order/<int:pk>/', views.create_service_order, name='create_service_order'),
    path('create_order/<int:pk>/', views.create_order, name='create_order'),
    path('register/', views.register, name='register'),
    path('supplies/<int:pk>/', views.supplies, name='supplies'),
    path('all_supplies/', views.all_supplies, name='all_supplies'),
    path('all_write_offs/', views.all_write_offs, name='all_write_offs'),
    path('all_sales/', views.all_sales, name='all_sales'),
    path('all_orders/', views.all_orders, name='all_orders'),


]

main/models.py
import datetime

from django.contrib.auth.models import AbstractUser
from django.db import models


# роли
class Roles(models.Model):
    name = models.CharField(max_length=50, verbose_name='Роль', blank=True, null=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Роль'
        verbose_name_plural = 'Роли'


# филиалы
class Filials(models.Model):
    city = models.CharField(max_length=50, verbose_name='Город', blank=True, null=True)
    street = models.CharField(max_length=50, verbose_name='Улица', blank=True, null=True)
    house = models.CharField(max_length=50, verbose_name='Дом', blank=True, null=True)
    email = models.CharField(max_length=50, verbose_name='Email', blank=True, null=True)
    phone = models.CharField(max_length=50, verbose_name='Телефон', blank=True, null=True)

    def __str__(self):
        return f'{self.city} {self.street} {self.house}'

    class Meta:
        verbose_name = 'Филиал'
        verbose_name_plural = 'Филиалы'


# пользователи
class Users(AbstractUser):
    patronymic = models.CharField(max_length=50, verbose_name='Отчество', blank=True, null=True)
    phone = models.CharField(max_length=50, verbose_name='Телефон', blank=True, null=True)
    role = models.ForeignKey(Roles, on_delete=models.CASCADE, verbose_name='Роль', blank=True, null=True)
    filial = models.ForeignKey(Filials, on_delete=models.CASCADE, verbose_name='Филиал', blank=True, null=True)

    def __str__(self):
        return f'{self.last_name} {self.first_name} {self.role}'

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'


# услуги
class Services(models.Model):
    name = models.CharField(max_length=50, verbose_name='Название', blank=True, null=True)
    cost = models.CharField(max_length=50, verbose_name='Стоимость', blank=True, null=True)
    description = models.TextField(verbose_name='Описание', blank=True, null=True)

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'Услуга'
        verbose_name_plural = 'Услуги'


# заказы на услуги
class Service_order(models.Model):
    client = models.ForeignKey(Users, on_delete=models.CASCADE, verbose_name='Клиент', blank=True, null=True)
    service = models.ForeignKey(Services, on_delete=models.CASCADE, verbose_name='Услуга', blank=True, null=True)
    filial = models.ForeignKey(Filials, on_delete=models.CASCADE, verbose_name='Филиал', blank=True, null=True)
    registration_date = models.DateField(verbose_name='Дата заявки', blank=True, null=True)
    date_completion = models.DateField(verbose_name='Дата выполнения', blank=True, null=True)
    cost = models.FloatField(verbose_name='Стоимость', blank=True, null=True)

    def __str__(self):
        return f'{self.client} {self.service}'

    class Meta:
        verbose_name = 'Заказ на услугу'
        verbose_name_plural = 'Заказы на услуги'


# типы товаров
class Types_products(models.Model):
    name = models.CharField(max_length=50, verbose_name='Название', blank=True, null=True)

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'Тип товара'
        verbose_name_plural = 'Типы товаров'


# товары
class Products(models.Model):
    name = models.CharField(max_length=50, verbose_name='Название', blank=True, null=True)
    type_product = models.ForeignKey(Types_products, on_delete=models.CASCADE, verbose_name='Тип продукта', blank=True,
                                     null=True)
    cost = models.FloatField(verbose_name='Стоимость', blank=True, null=True)
    photo = models.ImageField(upload_to='products', verbose_name='Фото', blank=True, null=True)
    stock_balance = models.IntegerField(verbose_name='Остаток на складе', blank=True, null=True)
    sheif_life = models.IntegerField(verbose_name='Срок годности', blank=True, null=True)

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'


# заказы
class Product_order(models.Model):
    client = models.ForeignKey(Users, on_delete=models.CASCADE, verbose_name='Клиент', blank=True, null=True)
    product = models.ForeignKey(Products, on_delete=models.CASCADE, verbose_name='Продукт', blank=True, null=True)
    filial = models.ForeignKey(Filials, on_delete=models.CASCADE, verbose_name='Филиал', blank=True, null=True)
    registration_date = models.DateField(verbose_name='Дата заявки', blank=True, null=True)
    date_completion = models.DateField(verbose_name='Дата выполнения', blank=True, null=True)
    cost = models.FloatField(verbose_name='Стоимость', blank=True, null=True)
    quantity = models.IntegerField(verbose_name='Количество', blank=True, null=True)

    def __str__(self):
        return f'{self.client} {self.product} {self.quantity}'

    # при сохранении дата выполнения равна дата заявка + 3 дня
    def save(self, *args, **kwargs):
        self.date_completion = self.registration_date + datetime.timedelta(days=3)

        # создание записи в таблице продаж
        sale = Sales()
        sale.product = self.product
        sale.filial = self.filial
        sale.date = self.date_completion
        sale.cost = self.cost
        sale.save()

        write_offs = Write_offs()
        write_offs.product = self.product
        write_offs.filial = self.filial
        write_offs.date = self.date_completion
        write_offs.quantity = self.quantity
        write_offs.save()

        super().save(*args, **kwargs)

    class Meta:
        verbose_name = 'Заказ на товар'
        verbose_name_plural = 'Заказы на товары'



# продажи
class Sales(models.Model):
    product = models.ForeignKey(Products, on_delete=models.CASCADE, verbose_name='Продукт', blank=True, null=True)
    filial = models.ForeignKey(Filials, on_delete=models.CASCADE, verbose_name='Филиал', blank=True, null=True)
    date = models.DateField(verbose_name='Дата', blank=True, null=True)
    cost = models.FloatField(verbose_name='Стоимость', blank=True, null=True)

    def __str__(self):
        return f'{self.product} {self.filial} {self.date} {self.cost}'

    class Meta:
        verbose_name = 'Продажа'
        verbose_name_plural = 'Продажи'


# списания
class Write_offs(models.Model):
    product = models.ForeignKey(Products, on_delete=models.CASCADE, verbose_name='Продукт', blank=True, null=True)
    filial = models.ForeignKey(Filials, on_delete=models.CASCADE, verbose_name='Филиал', blank=True, null=True)
    date = models.DateField(verbose_name='Дата', blank=True, null=True)
    quantity = models.IntegerField(verbose_name='Количество', blank=True, null=True)

    def __str__(self):
        return f'{self.product} {self.filial} {self.date} {self.quantity}'

    class Meta:
        verbose_name = 'Списание'
        verbose_name_plural = 'Списания'


# поставки
class Supplies(models.Model):
    delivery_date = models.DateField()
    filial = models.ForeignKey(Filials, on_delete=models.CASCADE, verbose_name='Филиал', blank=True, null=True)

    def __str__(self):
        return f'{self.filial} {self.delivery_date}'

    class Meta:
        verbose_name = 'Поставка'
        verbose_name_plural = 'Поставки'


# поставки товаров
class SuppliesItems(models.Model):
    product = models.ForeignKey(Products, on_delete=models.CASCADE, verbose_name='Продукт', blank=True, null=True)
    supplies = models.ForeignKey(Supplies, on_delete=models.CASCADE, verbose_name='Поставка', blank=True, null=True)
    quantity = models.IntegerField(verbose_name='Количество', blank=True, null=True)

    def __str__(self):
        return f'{self.product} {self.supplies} {self.quantity}'

    class Meta:
        verbose_name = 'Поставка товара'
        verbose_name_plural = 'Поставки товаров'

templates/create_order.html
{% extends "navbar.html" %}
{% block content %}
    <div class="container">
        <form method="post">
            {% csrf_token %}

            {{ supplies_form.as_p }}

            {{ supplies_items_formset.management_form }}
            <div id="supplies-items-formset">
                {% for form in supplies_items_formset %}
                    <div class="form-row">
                        {{ form.as_table }}
                    </div>
                {% endfor %}
            </div>

            <button type="button" class="btn btn-outline-success" id="add-form">Добавить</button>

            <input type="submit" class="btn btn-outline-primary" value="Создать">
        </form>

        <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.formset/1.2.2/jquery.formset.js"></script>
        <script>
            $(document).ready(function () {
                $('#add-form').click(function () {
                    // Находим контейнер для формсета
                    var formsetTable = $('#supplies-items-formset');

                    // Клонируем последнюю форму и обновляем номера полей
                    var newForm = formsetTable.find('.form-row:first').clone();
                    var totalForms = formsetTable.find('.form-row').length;

                    // Изменение атрибутов name и id для каждого элемента формы
                    newForm.find('input, select').each(function () {
                        var prefix = 'supplies_items';
                        var name = $(this).attr('name').replace(/-\d+-/g, '-' + totalForms + '-');
                        var id = 'id_' + name;
                        $(this).attr({'name': name, 'id': id}).val('').removeAttr('checked');
                        console.log($(this).attr('name'));
                    });

                    // Вставляем новую форму в формсет
                    formsetTable.append(newForm);

                    // Обновляем значение TOTAL_FORMS
                    $('#id_supplies_items-TOTAL_FORMS').val(totalForms + 1);
                    console.log($('#id_supplies_items-TOTAL_FORMS').val());
                });
            });
        </script>
    </div>
{% endblock %}

templates/filials.html
{% extends 'navbar.html' %}

{% block content %}
    <div class="container">
        <table class="table">
            <thead>
            <tr>
                <th scope="col">ID</th>
                <th scope="col">Город</th>
                <th scope="col">Улица</th>
                <th scope="col">Дом</th>
                <th scope="col">Email</th>
                <th scope="col">Телефон</th>
                <th scope="col">Управляющий</th>
            </tr>
            </thead>
            <tbody>
            {% for filial in filials %}
                <tr>
                    <th scope="row">{{ filial.id }}</th>
                    <td>{{ filial.city }}</td>
                    <td>{{ filial.street }}</td>
                    <td>{{ filial.house }}</td>
                    <td>{{ filial.email }}</td>
                    <td>{{ filial.phone }}</td>
                    <td>{{ user.filial }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

templates/index.html
{% extends 'navbar.html' %}

{% block content %}
    <div class="content-container" style="margin-top: 20px">
        
    </div>
{% endblock %}

templates/login.html
<!DOCTYPE html>
<html>
<head>
    <title>Login</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-lg-4">
            <h2 class="mb-4">Авторизация</h2>
            <form method="post" class="mb-3">
                {% csrf_token %}
                <div class="mb-3">
                    <label for="username" class="form-label">Логин</label>
                    <input type="text" name="username" id="username" class="form-control">
                </div>
                <div class="mb-3">
                    <label for="password" class="form-label">Пароль</label>
                    <input type="password" name="password" id="password" class="form-control">
                </div>
                <button type="submit" class="btn btn-primary">Войти</button>
            </form>
        </div>
    </div>
</div>
</body>
</html>

templates/navbar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Цветочный магазин</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
            crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.7.1.js"
            integrity="sha256-eKhayi8LEQwp4NKxN+CfCh+3qOVUtJn3QNZ0TciWLP4="
            crossorigin="anonymous"></script>
    <style>
        /* Add custom CSS for white background */
        .content-container {
            background-color: white;
            padding: 20px; /* Adjust padding as needed */
            border-radius: 10px; /* Optional: Add rounded corners */
        }
    </style>
    <link rel="icon" type="image/x-icon" href="https://img.icons8.com/fluency/48/flower.png">
</head>
<body class="animate__animated animate__fadeIn animate__delay-2s" id="animated-bg">

<nav class="navbar navbar-expand-lg navbar-light bg-light" style="margin-bottom: 20px">

    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'index' %}">Лого</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ms-auto">
                <li class="nav-item"><a href="{% url 'index' %}" class="nav-link">Главная</a></li>
                <li class="nav-item"><a href="{% url 'products' %}" class="nav-link">Товары</a></li>
                <li class="nav-item"><a href="{% url 'services' %}" class="nav-link">Услуги</a></li>
                {% if  request.user.is_authenticated %}
                    <li class="nav-item"><a href="{% url 'orders' request.user.id %}" class="nav-link">Заказы</a>
                    </li>
                    <li class="nav-item"><a href="{% url 'logout' %}" class="nav-link">Выйти</a></li>
                {% endif %}
                {% if request.user.role.name == 'Управляющий' and request.user.is_authenticated %}
                    <ul class="navbar-nav">
                        <li class="nav-item dropdown">
                            <button class="btn btn-light dropdown-toggle" data-bs-toggle="dropdown"
                                    aria-expanded="false">
                                Для управляющего
                            </button>
                            <ul class="dropdown-menu">

                                <li class="dropdown-item"><a href="{% url 'sales' request.user.filial.id %}"
                                                             class="nav-link">Продажи</a>
                                </li>
                                <li class="dropdown-item"><a href="{% url 'write_offs' request.user.filial.id %}"
                                                             class="nav-link">Списания</a></li>
                                <li class="dropdown-item"><a href="{% url 'supplies' request.user.filial.id %}"
                                                             class="nav-link">Поставки</a>
                                </li>
                                <li class="dropdown-item"><a href="{% url 'all_sales' %}"
                                                             class="nav-link">Продажи общие</a>
                                </li>
                                <li class="dropdown-item"><a href="{% url 'all_write_offs' %}"
                                                             class="nav-link">Списания общие</a>
                                </li>
                                <li class="dropdown-item"><a href="{% url 'all_supplies' %}"
                                                             class="nav-link">Поставки общие</a>
                                </li>
                                <li class="dropdown-item"><a href="{% url 'all_orders' %}"
                                                             class="nav-link">Все заказы</a>
                                </li>

                                {% if user.is_superuser %}
                                    <li class="dropdown-item" {% if request.path == '/admin/' %}active{% endif %}">
                                    <a class="nav-link" href="{% url 'admin:index' %}">Админка</a>
                                {% endif %}
                            </ul>
                        </li>
                    </ul>
                {% endif %}
                {% if request.user.is_authenticated == False %}
                    <li class="nav-item"><a href="{% url 'login' %}" class="nav-link">Войти</a></li>
                    <li class="nav-item"><a href="{% url 'register' %}" class="nav-link">Зарегистрироваться</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>


{% block content %}
{% endblock %}

<script>
    $(document).ready(function () {
        $(".supply").click(function () {
            // Найти ближайшую карточку и отобразить форму только внутри неё
            var card = $(this).closest('.card');
            card.find(".supply_form").removeAttr("hidden");
        });
    });
</script>
{#<script>#}
{#    // JavaScript to dynamically change the background gradient#}
{#    function updateBackground() {#}
{#        var body = document.getElementById('animated-bg');#}
{#        var currentTime = new Date().getTime();#}
{#        var gradient = 'linear-gradient(to right, ' +#}
{#            'rgb(' + Math.round(Math.sin(currentTime / 1000) * 100 + 150) + ', ' +#}
{#            Math.round(Math.sin(currentTime / 2000) * 100 + 150) + ', ' +#}
{#            Math.round(Math.sin(currentTime / 3000) * 100 + 150) + '), ' +#}
{#            'rgb(' + Math.round(Math.sin(currentTime / 4000) * 100 + 150) + ', ' +#}
{#            Math.round(Math.sin(currentTime / 5000) * 100 + 150) + ', ' +#}
{#            Math.round(Math.sin(currentTime / 6000) * 100 + 150) + '))';#}
{##}
{#        body.style.background = gradient;#}
{#        requestAnimationFrame(updateBackground);#}
{#    }#}
{##}
{#    // Initial call to start the animation#}
{#    updateBackground();#}
{#</script>#}

</body>
</html>

templates/orders.html
{% extends 'navbar.html' %}

{% block content %}

       <div class="content-container">
        <h2>Заказы товаров</h2>
        {% if products_error %}
            <div class="alert alert-info" role="alert">
                {{ products_error }}
            </div>
        {% else %}
            <table class="table table-striped">
                <thead>
                <tr>
                    <th scope="col">№</th>
                    <th scope="col">Дата заявки</th>
                    <th scope="col">Дата выполнения</th>
                    <th scope="col">Товар</th>
                    <th scope="col">Стоимость</th>
                    <th scope="col">Количество</th>
                    <th scope="col">Филиал</th>
                    {% if it_all %}
                        <th scope="col">Клиент</th>
                    {% endif %}

                </tr>
                </thead>
                <tbody>
                {% for order in orders %}
                    <tr>
                        <th scope="row">{{ order.id }}</th>
                        <td>{{ order.registration_date }}</td>
                        <td>{{ order.date_completion }}</td>
                        <td>{{ order.product }}</td>
                        <td>{{ order.cost }}</td>
                        <td>{{ order.quantity }}</td>
                        <td>{{ order.filial }}</td>
                        {% if it_all %}
                            <td>{{ order.client }}</td>
                        {% endif %}
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        {% endif %}


        <h2>Заказы услуг</h2>
        {% if services_error %}
            <div class="alert alert-info" role="alert">
                {{ services_error }}
            </div>
        {% else %}
            <table class="table table-striped">
                <thead>
                <tr>
                    <th scope="col">№</th>
                    <th scope="col">Дата заявки</th>
                    <th scope="col">Дата исполнения</th>
                    <th scope="col">Услуга</th>
                    <th scope="col">Стоимость</th>
                    <th scope="col">Филиал</th>
                    {% if it_all %}
                        <th scope="col">Клиент</th>
                    {% endif %}

                </tr>
                </thead>
                <tbody>
                {% for service in services %}
                    <tr>
                        <th scope="row">{{ service.id }}</th>
                        <td>{{ service.registration_date }}</td>
                        <td>{{ service.date_completion }}</td>
                        <td>{{ service.service }}</td>
                        <td>{{ service.cost }}</td>
                        <td>{{ service.filial }}</td>
                        {% if it_all %}
                            <td>{{ service.client }}</td>
                        {% endif %}
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        {% endif %}

    </div>

{% endblock %}
    

templates/products.html
{% extends 'navbar.html' %}



{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-12">
                <h1>Каталог товаров</h1>
            </div>
        </div>
    </div>

    {% if error %}
        <div class="row justify-content-center">
            <div class="col-9">
                <div class="alert alert-danger" role="alert">
                    {{ error }}
                </div>
            </div>
        </div>
    {% endif %}

    {% if success %}
        <div class="row justify-content-center">
            <div class="col-9 items-center">
                <div class="alert alert-success" role="alert">
                    {{ success }}
                </div>
            </div>
        </div>
    {% endif %}

    {% if success_supply %}
        <div class="row justify-content-center">
            <div class="col-9 items-center">
                <div class="alert alert-success" role="alert">
                    {{ success_supply }}
                </div>
            </div>
        </div>

    {% endif %}
    <div class="container">
        <div class="row">
            {% for p in products %}
                <div class="col-4">
                    <div class="card mb-4 d-flex flex-fill" id="card_{{ p.id }}">
                        <img src="{{ p.photo.url }}" class="card-img-top" alt="{{ p.name }}"
                             style="max-height: 200px; object-fit: cover;">
                        <div class="card-body">
                            <h5 class="card-title">{{ p.name }}</h5>
                            <h6 class="card-title">{{ p.type_product }}</h6>
                            <ul class="list-group list-group-flush">
                                <li class="list-group-item">Стоимость: {{ p.cost }} руб.</li>
                                <li class="list-group-item">Остаток: {{ p.stock_balance }}</li>
                                <li class="list-group-item">Срок годности: {{ p.sheif_life }} дней</li>
                            </ul>
                            {% if p.stock_balance > 0 %}
                                {% if request.user.is_authenticated %}
                                    <form method="post" action="{% url 'create_order' p.id %}">
                                        {% csrf_token %}
                                        <input type="hidden" name="product_id" value="{{ p.id }}">
                                        <label for="product_count">Количество</label>
                                        <input type="number" name="product_count" value="1" min="1"
                                               max="{{ p.stock_balance }}"
                                               class="form-control">
                                        <label for="filial">Филиал, в котором планируете забирать</label>
                                        <select name="filial" class="form-control">
                                            {% for f in filials %}
                                                <option value="{{ f.id }}">{{ f.city }} {{ f.street }}</option>
                                            {% endfor %}
                                        </select>
                                        <button type="submit" class="btn btn-outline-success mt-2">Купить</button>
                                    </form>

                                    {% if request.user.role.name == 'Управляющий' %}
                                        <a class="btn btn-outline-info mt-2 supply">Заказать</a>
                                    {% endif %}
                                {% else %}
                                    <div class="alert alert-info mt-2" role="alert">
                                        Для заказа товара необходимо авторизоваться
                                    </div>
                                {% endif %}
                            {% else %}
                                <div class="alert alert-danger mt-2" role="alert">
                                    Товара нет в наличии
                                </div>
                                {% if request.user.role.name == 'Управляющий' %}
                                    <a class="btn btn-outline-info mt-2 supply">Заказать</a>
                                {% endif %}

                            {% endif %}
                            <div class="container supply_form" hidden="hidden">
                                {% if request.user.role.name == 'Управляющий' %}
                                    <form method="post" action="{% url 'create_supply' p.id %}">
                                        {% csrf_token %}
                                        <label for="product_count">Количество</label>
                                        <input type="number" name="product_count" value="1" min="1"
                                               class="form-control">
                                        <label for="filial">Филиал, в который необходимо заказать</label>
                                        <select name="filial" class="form-control">
                                            {% for f in filials %}
                                                <option value="{{ f.id }}">{{ f.city }} {{ f.street }}</option>
                                            {% endfor %}
                                        </select>
                                        <label for="date">Дата поставки</label>
                                        <input type="date" name="delivery_date" class="form-control">
                                        <button type="submit" class="btn btn-outline-success mt-2">Заказать</button>
                                    </form>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

templates/supplies.html
{% extends 'navbar.html' %}

{% block content %}

    <div class="container">
        <h2>Поставки</h2>

        {% for delivery_date, supplies_list in supplies_group.items %}
            <h2>{{ delivery_date }}</h2>
            <div class="card-deck">
                {% for supply in supplies_list %}
                    <div class="card" style="margin-top: 5px;">
                        <div class="card-body">
                            <h5 class="card-text">Товар: {{ supply.suppliesitems_set.first.product.name }}</h5>
                            <p class="card-text">Филиал: {{ supply.filial }}</p>
                            <p class="card-text">Количество: {{ supply.suppliesitems_set.first.quantity }}</p>
                        </div>
                    </div>
                {% endfor %}
            </div>
        {% endfor %}
    </div>


{% endblock %}

templates/supply_list.html
<html lang="ru">
<head>
    <meta charset="utf-8">
    <title>Список поставок</title>
</head>
<body>

<h1>Список поставок</h1>

{% for supply in supplies %}
    <h2>Поставка #{{ supply.id }} - Дата: {{ supply.delivery_date }} - Филиал: {{ supply.filial }}</h2>
    <ul>
        {% for item in supply.suppliesitems_set.all %}
            <li>{{ item.product }} - Количество: {{ item.quantity }}</li>
        {% endfor %}
    </ul>
    <hr>
{% endfor %}

</body>
</html>